require 'spec_helper'

describe AuthSystem do
  it 'can be generated by a factory and has a full key set' do
    auth_system = FactoryBot.create :auth_system

    expect(auth_system).to be

    expect(auth_system.internal_private_key).to be_present
    expect(auth_system.internal_public_key).to be_present

    expect(auth_system.external_private_key).to be_present
    expect(auth_system.external_public_key).to be_present
  end
end
